### ISSUE TITLE
Книжка?

### ISSUE THREAD

**Issue by kanadeiar** [Umrikhin/book-asp-net-core#1]
Здравствуйте! А что за книжка? Добавьте, пожалуйста, файл ридми пожалуйста в корень репозитория с названием и если возможно изображением.

**Comment by Umrikhin** [comment]
Добрый день. Это примеры из проекта, который пока в работе. Книги еще нет. Даже нет договора с издательством. 
Не ожидал, что мои публикации смотрят. Пока закрою репозиторий до момента выхода книги, если это конечно произойдет.
